name: 'Lint'
description: 'Install and run the lint'
runs:
  using: "composite"
  steps:
    - name: Install golangci-lint
      env:
        VERSION: 1.41.1
      run: |
        curl https://github.com/golangci/golangci-lint/releases/download/v${VERSION}/golangci-lint-${VERSION}-linux-amd64.tar.gz -o golangci-lint-${VERSION}-linux-amd64.tar.gz
        tar xvzf golangci-lint-${VERSION}-linux-amd64.tar.gz
        mv golangci-lint-${VERSION}-linux-amd64/golangci-lint golangci-lint
      shell: bash
    - name: Run lint
      run: ./golangci-lint run
      shell: bash
