name: 'Lint'
description: 'Install and run the lint'
runs:
  using: "composite"
  steps:
    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.41.1
      shell: bash
    - name: Run lint
      run: golangci-lint run
      shell: bash